services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: case

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: case
      ME_CONFIG_MONGODB_URL: mongodb://root:case@mongo:27017/

  backend:
    build: ./todo-backend
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment: 
      DATABASE_URL: mongodb://root:case@mongo:27017/
      PORT: 3001