services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: case
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: case
      ME_CONFIG_MONGODB_URL: mongodb://root:case@mongo:27017/

  backend:
    build: ./todo-backend
    command: npm run dev
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment: 
      DATABASE_URL: mongodb://root:case@mongo:27017/
      PORT: 3001
  
  frontend:
    build: ./todo-frontend
    command: npx serve build
    ports:
      - "3000:3000"
    depends_on:
      - backend
      